apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod-predictor
  namespace: proactive-autoscaler
spec:
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pod-predictor
              image: adham541/pod-predictor:1.3
              command: ["python", "PredictorController.py"]
          restartPolicy: OnFailure
